// # Euler problem 2
// # Sum of all even fibonacci numbers below an upper limit
// # Each new term in the Fibonacci sequence is generated by adding the 
// # previous two terms. By starting with 1 and 2, the first 10 terms will be:
// # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// # By considering the terms in the Fibonacci sequence whose values do not 
// # exceed four million, find the sum of the even-valued terms.

import java.util.Scanner;

public class euler2 {
		public static void main(String[] args) {
			int sum, x, y, z, target;
			
			System.out.println("Enter upper limit number:  ");
			Scanner scanner = new Scanner(System.in);
			String num = scanner.nextLine();
			System.out.println("Fibonacci sums for target " + num); 
			target = Integer.parseInt(num);
			
			sum = 0;
			x = 1;
			y = 1;
			z = 0;
			while ( z <= target ) {
				System.out.println(z);
				z = x + y;
				if (z % 2 == 0) {
					sum = sum + z;
				}
				x = y;
				y = z;
			}
			System.out.println("The sum of even fibonacci numbers are " + sum	);
		}
}